apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    devopscontrol/app: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        devopscontrol/app: "true"
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.name }}
          ports:
            - containerPort: {{ .Values.image.port }}
