apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: {{ .Values.image.port }}
      targetPort: {{ .Values.image.port }}
